service:
  name: noticonn-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline


provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  profile: noticonn
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::noticonn/*" # add

functions:
  getAllEvents:
    handler: src/handler/event.getAllEvents
    package:
      include:
        - src/**
    events:
      - http:
          method: get
          path: allEvents
  getEvents:
    handler: src/handler/event.getEvents
    package:
      include:
        - src/**
    events:
      - http:
          method: get
          path: events
  save:
    handler: src/handler/event.save
    package:
      include:
        - src/**
    events:
      - http:
          method: get
          path: save
