service:
  name: noticonn-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  defaultStage: dev
  profiles:
    dev: noticonn-dev
    prd: noticonn
  env:
    dev: ${file(./serverless/env/dev.yml)}
    prd: ${file(./serverless/env/prd.yml)}

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${self:provider.stage}}
  environment:
    BUCKET: ${self:custom.env.${self:provider.stage}.BUCKET}
    EVENT_FILE: ${self:custom.env.${self:provider.stage}.EVENT_FILE}
    SINCE_ID_FILE: ${self:custom.env.${self:provider.stage}.SINCE_ID_FILE}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:custom.env.${self:provider.stage}.BUCKET}/*" # add

functions:
  getEvents:
    handler: src/handler/event.getEvents
    package:
      include:
        - src/**
    events:
      - http:
          method: get
          path: events
  save:
    handler: src/handler/event.save
    package:
      include:
        - src/**
    events:
      - schedule: cron(0/10 * * * ? *)
