jobs:
  setup:
    working_directory: /tmp
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout # ソースコードを作業ディレクトリにチェックアウトする特別なステップ
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # 依存関係キャッシュを復元する特別なステップ
          # 依存関係キャッシュについては https://circleci.com/docs/ja/2.0/caching/ をお読みください
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm
          command: npm install
      - run:
          name: install-yarn
          command: npm install yarn
      - save_cache: # 依存関係キャッシュを保存する特別なステップ
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  deploy-lambda:
    steps:
      - run:
        name: deploy with serverless
        command: make deploy-prd
workflows:
  version: 2
  approval-deploy-with-serverless:
    jobs:
      - setup
      - request-deploy:
          type: approval  # approvalを設定したjob
      - deploy-lambda:
          filters:
            branches:
              only: master
